### ISSUE TITLE
issues to setuid/setgid for vassals

### ISSUE THREAD

**Issue by yilinxiong** [Kwpolska/ansible-nginx-uwsgi#3]
Hi There,

I just noticed, you are running uwsgi emperor with the uwsgi user, I don't think you can setuid/setgid for the vassals as non-root user. I'm looking for a solution which I can run emperor as the non-root user, meanwhile the emperor can set different uids/gids for the vassals. But I still not find the solution yet, cureently just run emperor as the root user. Does your playbook work for you? Are the vassals can run as different users while emperor running as non-root user?

Any suggestions & ideas from your side will be very appreciated.

**Comment by yilinxiong** [comment]
Well, I just found the answer [here](http://uwsgi.unbit.narkive.com/JFZNyqOV/tyrant-mode-vassals-not-using-uid-specified-in-their-configuration)

I think it would be better to use the [emperor-tyrant mode](http://uwsgi-docs.readthedocs.io/en/latest/Emperor.html#tyrant-mode-secure-multi-user-hosting) to host multi-user applications if possible :)

**Comment by Kwpolska** [comment]
The playbook works fine for me, as I *want* to run all of my vassals under the `uwsgi` user. This is the correct/good-enough approach for most places. I suppose you’re building some shared hosting space and want the uwsgi vassals to run as your customers’ specfic user accounts? In that case, feel free to fork the playbook or otherwise modify it for your needs. Keeping permissions right for files is much harder than a few config entries (there’s a chance reckless copy-paste will create a root/root file).

**Comment by Kwpolska** [comment]
PS. you can also try setting the Emperor to run as root/root and vassals to whatever/nginx in their specific config files (please test that setup on your own.)

**Comment by Kwpolska** [comment]
PPS. I [updated](https://github.com/Kwpolska/chriswarrick.com/commit/e6293ccb#diff-85a23feb90a196333da9bcbbc9045b0a) the original blog post’s mention of `emperor-tyrant` to one that explains how it works, thanks for pointing this out.
